target: main.cpp HexVector.cpp HexVector.h AbstractHex.cpp AbstractHex.h HexArray1D.cpp HexArray1D.h HexAdapter.cpp HexAdapter.h
	g++ -std=c++11 main.cpp HexVector.cpp AbstractHex.cpp HexArray1D.cpp  HexAdapter.cpp -o test
	./test